name: practice-ci-cd
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://github.com/apix23/github-actions-masterclass.git
          echo "Changing some content"
          pwd 
          ls -la

      